
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      - run: ./scripts/build.sh

#==============================================================================
# UNCOMMENT THIS SECTION ONCE WE HAVE PUBLISHING TO NPM.ORG
#==============================================================================

    # - run: yarn install --frozen-lockfile
    # - run: yarn lint-verify
    # - run: yarn build
    # - run: yarn test
    # - run: yarn publish-verify
